spring.application.name=miGaleria

# URL de la base de datos (asegúrate de que el nombre 'tu_base_de_datos' coincida con el que creaste en pgAdmin)
spring.datasource.url=jdbc:postgresql://localhost:5432/miGaleria
spring.datasource.username=postgres
spring.datasource.password=postgres

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Actualiza la base de datos según tus clases Java (muy útil en desarrollo)
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de IntelliJ las consultas SQL que hace Spring (para depurar)
spring.jpa.show-sql=true

# Formatea el SQL de la consola para que sea legible
spring.jpa.properties.hibernate.format_sql=true

# Dialecto de la base de datos
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Puerto donde corre tu aplicación
server.port=8080

# Esto ayuda a que Spring gestione mejor las rutas de los archivos estáticos
spring.web.resources.static-locations=classpath:/static/

spring.data.mongodb.uri=mongodb://localhost:27017/migaleria_db
